### ISSUE TITLE
method field not found. Error 

### ISSUE THREAD

**Issue by Rem559** [metahashorg/Node-InfrastructureTorrent#6]
error:
method field not found. Error at file /home/user/torrent_w_node/src/Server.cpp line 325

System ubuntu 18.04.4. 
Node-InfrastructureTorrent release v1.5

**Comment by Rem559** [comment]
Incorrect func eth_blockNumber. Error at file /home/user/torrent_w_node/src/Server.cpp line 402

**Comment by Rem559** [comment]
reinstall ubuntu helps

**Comment by Rem559** [comment]
Полная переустановка системы не помогла, ошибки  проявились вновь.  
Сomplete reinstallation did't help's, errors reappeared.

**Comment by sv-91** [comment]
Эта ошибка означает, что на ноду приходят неправильные запросы. Виновата не нода, а тот, кто эти запросы шлет

**Comment by Rem559** [comment]
Спасибо за пояснение!
