### ISSUE TITLE
compilation error  invalid use of ‘std::exception::exception’

### ISSUE THREAD

**Issue by Rem559** [metahashorg/Node-InfrastructureTorrent#7]
/tmp/torrent_node/src/Server.cpp: In member function ‘virtual bool Server::run(int, sniper::mhd::MHD::Request&, sniper::mhd::MHD::Response&)’:
/tmp/torrent_node/src/Server.cpp:412:23: error: invalid use of ‘std::exception::exception’
         LOGDEBUG << e.exception;
                       ^~~~~~~~~
/tmp/torrent_node/src/Server.cpp:413:63: error: invalid use of ‘std::exception::exception’
         mhd_resp.data = genErrorResponse(requestId, -32602, e.exception + ". Url: " + url);
                                                               ^~~~~~~~~
src/CMakeFiles/torrent_node.dir/build.make:101: recipe for target 'src/CMakeFiles/torrent_node.dir/Server.cpp.o' failed
make[2]: *** [src/CMakeFiles/torrent_node.dir/Server.cpp.o] Error 1
make[2]: *** Ожидание завершения заданий…
CMakeFiles/Makefile2:759: recipe for target 'src/CMakeFiles/torrent_node.dir/all' failed
make[1]: *** [src/CMakeFiles/torrent_node.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sv-91** [comment]
What is the version of the compiler with which you compile the sources?

**Comment by Rem559** [comment]
gcc-8 (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0

**Comment by sv-91** [comment]
You can try in the file common_utils/check.h:11 to replace exception with something else globally across all files.
While I do not know what the problem may be related to

**Comment by Rem559** [comment]
ok, thanks
